#[build]
#target = "x86_64-unknown-uefi"

[build]
target = "aarch64-unknown-uefi"

[target.x86_64-unknown-uefi]
rustflags = ["-C", "link-args=/debug:dwarf"]

[target.aarch64-unknown-uefi]
rustflags = ["-C", "link-args=/debug:dwarf"]
