[build]
target = "aarch64-unknown-none"

[target.x86_64-unknown-uefi]
rustflags = ["-C", "link-args=/debug:dwarf"]
runner = "qemu-system-x86_64 -m 2048M -serial mon:stdio -bios ovmf/OVMF_x86_64.fd -device driver=e1000,netdev=n0 -netdev user,id=n0 -kernel "

[target.aarch64-unknown-uefi]
rustflags = ["-C", "link-args=/debug:dwarf"]
runner = "qemu-system-aarch64 -m 2048M -cpu cortex-a76 -M virt,gic-version=3 -bios ovmf/OVMF_aarch64.fd -device virtio-net,netdev=net0 -serial mon:stdio -device ramfb -netdev user,id=net0 -usb -device usb-ehci,id=ehci -device usb-kbd -kernel "

# Test PAC with '-Zbranch-protection=bti,pac-ret,leaf' and compile with -Zbuild-std=core
[target.aarch64-unknown-none]
rustflags = ['-Clink-arg=-Tsrc/arch/aarch64/virt.ld', '-Crelocation-model=pic', '-Clink-arg=-pie', '-Clink-arg=-znotext']
#runner = "qemu-system-aarch64 -m 2048M -cpu cortex-a76 -smp 4 -M virt,gic-version=3 -device virtio-net,netdev=net0 -serial mon:stdio -netdev user,id=net0 -device ramfb -usb -device usb-ehci,id=ehci -device usb-kbd -s -S -kernel "
#runner = "echo Running like this will crash your system. Please use start_aarch64_qemu.sh to run "
runner = "sh start_aarch64_qemu.sh"

[target.aarch64-unknown-none-softfloat]
rustflags = ['-Clink-arg=-Tsrc/arch/aarch64/virt.ld', '-Crelocation-model=pic', '-Clink-arg=-pie', '-Clink-arg=-znotext']
#runner = "qemu-system-aarch64 -m 2048M -cpu cortex-a76 -smp 4 -M virt,gic-version=3 -device virtio-net,netdev=net0 -serial mon:stdio -netdev user,id=net0 -usb -device usb-ehci,id=ehci -device usb-kbd -device ramfb -kernel "
runner = "echo Running like this will crash your system. Please use start_aarch64_qemu.sh to run "

[target.riscv64gc-unknown-none-elf]
rustflags = ['-Clink-arg=-Tsrc/arch/riscv64/virt.ld']
runner = "qemu-system-riscv64 -m 2048M -cpu rv64 -M virt -device virtio-net,netdev=net0 -serial mon:stdio -bios none -netdev user,id=net0 -usb -device usb-ehci,id=ehci -device usb-kbd -device ramfb -kernel "
