name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_aarch64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Build aarch64
      run: cargo build --target aarch64-unknown-none --verbose

  build_riscv64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    
    - name: Build riscv64
      run: cargo build --target riscv64gc-unknown-none-elf --verbose
